export enum AccountActionTypes {
  CHECK_PHONE = '@account/CHECK_PHONE',
  CHECK_PHONE_SUCCESS = '@account/CHECK_PHONE_SUCCESS',
  CHECK_PHONE_FAILURE = '@account/CHECK_PHONE_FAILURE',
  CHECK_CODE = '@account/CHECK_CODE',
  CHECK_CODE_FAILURE = '@account/CHECK_CODE_FAILURE',
  GET_USER = '@account/GET_USER',
  GET_USER_SUCCESS = '@account/GET_USER_SUCCESS',
  GET_USER_FAILURE = '@account/GET_USER_FAILURE',
  SET_USER = '@account/SET_USER',
  CLEAR_USER = '@account/CLEAR_USER',
  ERROR = '@account/ERROR',
  TOKEN_SET = '@token/set',
  TOKEN_ERROR = '@token/error',
  TOKEN_REFRESH = '@token/refresh',
  TOKEN_REFRESH_SUCCESS = '@token/refresh_success',
  TOKEN_REFRESH_ERROR = '@token/refresh_error',
}
