export enum AgencyActionTypes {
  LOAD_AGENCY = '@agency/LOAD',
  LOAD_IMPORTS_LOGS = '@agency/LOAD_IMPORTS_LOGS',
  LOAD_IMPORTS_LOGS_ERROR = '@agency/LOAD_IMPORTS_LOGS_ERROR',
  LOAD_IMPORTS_LOGS_SUCCESS = '@agency/LOAD_IMPORTS_LOGS_SUCCESS',
  SET_AGENCY = '@agency/SET',
  LOAD_AGENCY_ERROR = '@agency/LOAD_ERROR',
  SAVE_AGENCY = '@agency/SAVE',
  SAVE_AGENCY_SUCCESS = '@agency/SAVE_SUCCESS',
  SAVE_AGENCY_ERROR = '@agency/SAVE_ERROR',
  UPDATE_AGENCY = '@agency/UPDATE',
  RESET_AGENCY = '@agency/RESET',
  REMOVE_AGENT = '@agency/REMOVE_AGENT',
}
